<div class="mx-auto">
  <h1 class="text-center">Lista de Tarefas</h1>

  <?php foreach ($this->view["tarefas"] as $tarefas) :
    switch ($tarefas["status"]) {
      case "EM PROGRESSO":
        $badge_class = "info";
        break;
      case "FINALIZADA":
        $badge_class = "success";
        break;
      case "ABERTA":
        $badge_class = "secondary";
        break;
      default:
        $badge_class = null;
        break;
    }
  ?>
    <div class="col-md-12 pb-3">
      <div class="card">
        <div class="card-body">
          <?= $tarefas["title"] ?>
          <span class="badge badge-pill float-right badge-<?= $badge_class ?>"><?= $tarefas["status"] ?></span>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>